### ISSUE TITLE
OpenWeatherMap_ no data in Polisy v 5.8.0 (after SSD refashed for service)

### ISSUE THREAD

**Issue by danielhajas** [bpaauwe/udi-owm-poly#15]
Hello ,
My Polisy was recentlly serviced, (and SSD reflashed), it works now but OpenWeatherMap shows Disconected!
I had inserted my API Key from OpenWeatherMap, set my Longitude and latitude, elevation but... no data!
Please help, it work just fine a week ago, but no more. After freflashe, i have hard time seting it up again.
My Longitude and latitude are in this format: lat=43.651070&lon=-79.347015

I had this issue before but i had forgot how i had it work again, you helped last time too!
Tahnks

**Comment by bpaauwe** [comment]
Are there any errors in the OpenWeatherMap plug-in log?

**Comment by danielhajas** [comment]
The only one that i can see is Syntax Error. Please see attached the log fime
[OpenWeatherMap_2-2-2024_10259_PM.zip](https://github.com/bpaauwe/udi-owm-poly/files/14145330/OpenWeatherMap_2-2-2024_10259_PM.zip)

**Comment by danielhajas** [comment]
This is the last batch of errors:
2024-02-02 15:47:47,294 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2024-02-02 15:47:47,294 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d967c_1/./owm.py", line 10, in <module>
2024-02-02 15:47:47,295 MainThread udi_interface      ERROR    udi_interface:write: from nodes import owm
2024-02-02 15:47:47,296 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d967c_1/nodes/owm.py", line 17, in <module>
2024-02-02 15:47:47,297 MainThread udi_interface      ERROR    udi_interface:write: from nodes import owm_daily
2024-02-02 15:47:47,297 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d967c_1/nodes/owm_daily.py", line 8, in <module>
2024-02-02 15:47:47,298 MainThread udi_interface      ERROR    udi_interface:write: from nodes import et3
2024-02-02 15:47:47,299 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d967c_1/nodes/et3.py", line 1
2024-02-02 15:47:47,300 MainThread udi_interface      ERROR    udi_interface:write: (t + vaporRate), 2)
2024-02-02 15:47:47,300 MainThread udi_interface      ERROR    udi_interface:write: ^
2024-02-02 15:47:47,301 MainThread udi_interface      ERROR    udi_interface:write: SyntaxError
2024-02-02 15:47:47,301 MainThread udi_interface      ERROR    udi_interface:write: :
2024-02-02 15:47:47,302 MainThread udi_interface      ERROR    udi_interface:write: unmatched ')'

**Comment by bpaauwe** [comment]
It appears to be a corrupted file that's causing the error.  Try re-installing.  If that doesn't work you'll have to submit a ticket to UDI as your system is corrupting the file when installing from the release package.

**Comment by danielhajas** [comment]
Hi,

I uninstalled (delet) from Polyglot dashbpoard and then reinstalled it from my Purchased folder on Polyglot.
Still shows Disconected on the dashboard and the logs as shown here:
2024-02-02 17:21:40,147 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2024-02-02 17:21:40,148 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d967c_1/./owm.py", line 10, in <module>
2024-02-02 17:21:40,149 MainThread udi_interface      ERROR    udi_interface:write: from nodes import owm
2024-02-02 17:21:40,150 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d967c_1/nodes/owm.py", line 1
2024-02-02 17:21:40,151 MainThread udi_interface      ERROR    udi_interface:write: HUM', 'value': 0, 'uom': 22},   # humidity
2024-02-02 17:21:40,152 MainThread udi_interface      ERROR    udi_interface:write: ^
2024-02-02 17:21:40,153 MainThread udi_interface      ERROR    udi_interface:write: SyntaxError
2024-02-02 17:21:40,154 MainThread udi_interface      ERROR    udi_interface:write: :
2024-02-02 17:21:40,154 MainThread udi_interface      ERROR    udi_interface:write: invalid syntax

**Comment by danielhajas** [comment]
This is what i got after deleteng it and reinstalling it on Polyglot:
![Screenshot 2024-02-02 174920](https://github.com/bpaauwe/udi-owm-poly/assets/102629704/df06b017-7926-4657-bc88-1edc90f7d029)
![Screenshot 2024-02-02 175013](https://github.com/bpaauwe/udi-owm-poly/assets/102629704/d257cfe0-2dea-4880-9dd9-d5b458c56335)

**Comment by danielhajas** [comment]
It does not show OpenWeather Map on my Polisy. What to do ?

**Comment by danielhajas** [comment]
Also, initially i had 2 nodes that where not working properlly, OWM and TimData, after rebooting the Polisy TimeData works normal but OWM does not show anymore on my Polisy as i mentioned! Same Errors seem to persist.

**Comment by bpaauwe** [comment]
There are no syntax errors in the plug-in code.  You are seeing those because your system has corrupted the files when it installs the plug-in.  You'll have to submit a ticket to UDI so they can figure out what's wrong with your system.
