### ISSUE TITLE
Exception in thread Controller:

### ISSUE THREAD

**Issue by danvanklaveren** [bpaauwe/udi-owm-poly#2]
Running on ISY
Firmware Version: 5.0.15

Thread error after start of OpenWeatherMap. First time to get weather data works, then at some point later the following:
2019-08-12 06:23:02,678 [Controller] [INFO ] Updating Driver weather - GV4: 5.82 uom: 48
2019-08-12 06:23:02,680 [Controller] [ERROR] Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgc_interface/pgc_interface.py", line 795, in _parseInput
    self.shortPoll()
  File "./owm.py", line 115, in shortPoll
    self.query_conditions()
  File "./owm.py", line 197, in query_conditions
    self.update_driver('WINDDIR', jdata['wind']['deg'], self.uom['WINDDIR'])
KeyError: 'deg'
2019-08-12 06:23:05,294 [Drivers   ] [DEBUG] Sent Message: [prod/ns] : {"batch": {"status": [{"address": "weather", "driver": "CLITEMP", "value": "64.9", "uom": "17"}, {"address": "weather", "driver": "CLIHUM", "value": "82.0", "uom": "22"}, {"address": "weather", "driver": "BARPRES", "value": "1014.0", "uom": "118"}, {"address": "weather", "driver": "GV0", "value": "69.01", "uom": "17"}, {"address": "weather", "driver": "GV1", "value": "60.8", "uom": "17"}, {"address": "weather", "driver": "GV4", "value": "5.82", "uom": "48"}]}, "userId": "5acxxxxxxxxxxxxxxxxxxxxxx103", "topic": "prod/ns/openweathermap-0021b9022a0c-5", "profileNum": "5", "id": "00:XX:XX:XX:XX:0c"}

**Comment by bpaauwe** [comment]
Wind direction is sometime missing from the query response. With version 1.2.2, I've added some checking to make sure it exist before trying to use it.
